title: МатМех

markdown: kramdown
theme: minima

header_pages:
  - courses/terver/index.md
  - courses/alg/index.md
  - courses/cgg/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default