title: МатМех

markdown: kramdown
theme: minima

sections:
  - courses/index.md
  - courses/spec/index.md
  - calendar.md
  - about.md

courses:
  - courses/3/terver/index.md
  - courses/3/cgg/index.md
  - courses/3/loi/index.md
  - courses/3/physics/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default