title: МатМех

markdown: kramdown
theme: minima

header_pages:
  - courses/3/terver/index.md
  - courses/3/cgg/index.md
  - courses/3/loi/index.md
  - courses/3/physics/index.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: default